## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [55]:
## initially Lets import numpy

import numpy as np

In [57]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [58]:
print(arr)

[1 2 3 4 5]


In [60]:
type(arr)

numpy.ndarray

In [61]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [64]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [65]:
type(arr)

numpy.ndarray

In [66]:
## check the shape of the array

arr.shape

(3, 5)

### Indexing 

In [68]:
## Accessing the array elements

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [69]:
arr[2]

array([9, 7, 6, 8, 9])

In [71]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [73]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [74]:
arr[1:,:2]

array([[2, 3],
       [9, 7]])

In [75]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [76]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [77]:
arr[3:]=100

In [78]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [80]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]


array([1, 2, 2])

In [81]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
arr1=np.arange(0,10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
arr2=np.arange(0,10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [96]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [97]:
## random distribution
np.random.rand(3,3)

array([[0.4764204 , 0.16438808, 0.73815776],
       [0.02133366, 0.42807405, 0.27494683],
       [0.53153042, 0.98465507, 0.68226325]])

In [98]:
arr_ex=np.random.randn(4,4)

In [99]:
arr_ex

array([[-0.58198444, -1.57718417, -0.51896184, -1.0127303 ],
       [-2.14381405,  1.21164403,  0.22444776, -0.09937617],
       [ 1.76708723, -0.51758832,  2.4236487 , -1.06023416],
       [ 1.34803696, -0.46485788,  0.10665161, -0.73716448]])

In [101]:
#pip install seaborn

In [1]:
import seaborn as sns
import pandas as pd

In [2]:
sns.distplot(pd.DataFrame(arr_ex.reshape(16,1)))

NameError: name 'arr_ex' is not defined

In [ ]:
np.random.randint(0,100,8).reshape(4,2)

In [ ]:
np.random.random_sample((1,5))

In [35]:
# Create NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
# Basic statistics
mean_value = np.mean(arr1)
mean_value
median_value = np.median(arr1)
median_value
std_deviation = np.std(arr1)
std_deviation

1.4142135623730951

In [40]:
# Linear algebra operations
dot_product = np.dot(arr1, arr1)
matrix_multiplication = np.matmul(arr2, arr2.T)

In [41]:
# Random number generation
random_numbers = np.random.rand(5)

In [44]:
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 70000]}
df = pd.DataFrame(data)

In [45]:
# Basic statistics on DataFrame
mean_age = df['Age'].mean()
max_salary = df['Salary'].max()
summary_stats = df.describe()

In [46]:
# Filtering data
young_people = df[df['Age'] < 30]

In [54]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 70000]}

df = pd.DataFrame(data)

# Grouping and calculating mean for numeric columns
grouped_by_age = df.groupby('Age')['Salary'].mean()
grouped_by_age

Age
25    50000.0
30    60000.0
35    70000.0
Name: Salary, dtype: float64

In [49]:
# Merge two DataFrames
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Salary': [50000, 60000, 80000]})

In [52]:
merged_df = pd.merge(df1, df2, on='ID', how='inner')
merged_df

ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000

In [53]:
# Joining DataFrames
df3 = pd.DataFrame({'ID': [1, 2, 3], 'Address': ['123 Main St', '456 Oak St', '789 Pine St']})

joined_df = df1.join(df3.set_index('ID'), on='ID')